version: "3"

services:
    api-backendtest:
        image: backendtest:latest
        container_name: backendtestapi
        build: 
            context: ../src
            dockerfile: ../src/Dockerfile
        restart: always
        ports:
            - "5001:5001"
            - "80:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5001;http://+80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/backendtest.pfx
        volumes:
            - ./certs:/https:ro  
        depends_on: 
            - sql-server
    sql-server:
        image: microsoft/mssql-server-2019-linux:latest
        container_name: backendtest-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "!nov@2021"
            ACCEPT_EULA: "Y"   
        ports:
            - "1433:1433" 